workflows:
  default-workflow:
    name: Build and Test
    environment:
      flutter: 3.7.0  # 或者指定一个特定版本，例如 '3.10.0'
      xcode: latest    # 用于 iOS 构建
    scripts:
      - name: Clean the project
        script: flutter clean
      - name: Get dependencies
        script: flutter pub get
#      - name: Ensure latest Flutter SDK
#        script: flutter upgrade --force
      - name: Build APK
        script: flutter build apk --release --verbose

      - name: Build iOS App
        script: flutter build ios --release --no-codesign --verbose

      - name: Archive iOS App
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/Runner.xcarchive \
            archive

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/Runner.xcarchive \
            -exportPath $CM_BUILD_DIR \
            -exportOptionsPlist ios/exportOptions.plist

    artifacts:
      - $CM_BUILD_DIR/*.ipa
