name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # 保留手动触发选项

jobs:
  build:
    runs-on: macos-latest  # 使用 macOS 构建 iOS 和 Android 应用

    env:
      FLUTTER_VERSION: '3.7.0'

    steps:
      - name: Set up environment proxy  # 如果需要设置代理，请取消注释并填入你的代理信息
        run: |
          echo "http_proxy=http://127.0.0.1:7890" >> $GITHUB_ENV
        #  echo "https_proxy=http://your.proxy.host:your.proxy.port" >> $GITHUB_ENV
        # 如果不需要代理，可删除或注释上面这段代码

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Clean the project
        run: flutter clean

      - name: Get dependencies
        run: flutter pub get

      #- name: Ensure latest Flutter SDK  # 如果不需要强制升级，可以保留注释
      #  run: flutter upgrade --force
      # --release --verbose 
      - name: Build APK
        run: flutter build apk --stacktrace --debug

      - name: Build iOS App
        run: flutter build ios --release --no-codesign --verbose

      - name: Archive iOS App
        run: |
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -sdk iphoneos \
            -configuration Release \
            -archivePath ${{ github.workspace }}/Runner.xcarchive \
            archive

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath ${{ github.workspace }}/Runner.xcarchive \
            -exportPath ${{ github.workspace }} \
            -exportOptionsPlist ios/exportOptions.plist

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.ipa
          path: ${{ github.workspace }}/*.ipa
